name: Run Murder Scraper Until Server Busy

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start number (e.g. 0)"
        required: true
        default: "0"
      END:
        description: "End number (e.g. 100)"
        required: true
        default: "100"
      YEAR:
        description: "Year (e.g. 2024)"
        required: true
        default: "2024"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        env:
          START: ${{ inputs.START }}
          END: ${{ inputs.END }}
          YEAR: ${{ inputs.YEAR }}
        run: python scraper.py

      - name: Find the output CSV filename
        id: find_csv
        run: |
          FILE=$(ls charges_CR${{ inputs.YEAR }}_${{ inputs.START }}-*.csv | head -n 1)
          echo "csv_name=$FILE" >> $GITHUB_OUTPUT

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_csv.outputs.csv_name }}
          path: ${{ steps.find_csv.outputs.csv_name }}
