name: Run Murder Scraper Prox Change

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start number (e.g. 0)"
        required: true
        default: "0"
      END:
        description: "End number (e.g. 100)"
        required: true
        default: "100"
      YEAR:
        description: "Year (e.g. 2024)"
        required: true
        default: "2024"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        env:
          START: ${{ inputs.START }}
          END: ${{ inputs.END }}
          YEAR: ${{ inputs.YEAR }}
        run: python "scraper.py"

      - name: Upload all batch CSVs
        uses: actions/upload-artifact@v4
        with:
          name: all-batch-csvs
          path: |
            *.csv
