name: Workflow B - Continue Scraper

on:
  repository_dispatch:
    types: [continue-with-B]

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Read progress start value
        id: read-progress
        run: |
          START=$(cat progress.txt)
          echo "START=$START" >> $GITHUB_ENV
          echo "START read as: $START"

      - name: Run scraper
        env:
          START: ${{ env.START }}
          END: "170000"
          YEAR: "2024"
        run: python scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: charges-output-${{ env.START }}
          path: charges_CR*.csv

      - name: Trigger Workflow A
        if: always()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "continue-with-A"}'
