name: Workflow B - Continue Scraper

on:
  repository_dispatch:
    types: [continue-with-b]

jobs:
  run-scraper-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        env:
          START: ${{ github.event.client_payload.start }}
          END: ${{ github.event.client_payload.end }}
          YEAR: ${{ github.event.client_payload.year }}
        run: python scraper.py

      - name: Upload CSV results
        uses: actions/upload-artifact@v4
        with:
          name: charges-output
          path: |
            *.csv
            progress.txt
