name: Workflow A - Run Scraper

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start number"
        required: true
        default: "0"
      END:
        description: "End number"
        required: true
        default: "100"
      YEAR:
        description: "Year"
        required: true
        default: "2024"

jobs:
  run-scraper-a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraper
        env:
          START: ${{ inputs.START }}
          END: ${{ inputs.END }}
          YEAR: ${{ inputs.YEAR }}
        run: python scraper.py

      - name: Upload CSV results
        uses: actions/upload-artifact@v4
        with:
          name: charges-output
          path: |
            *.csv
            progress.txt

      - name: Trigger Workflow B
        if: always()
        run: |
          NEXT_START=$(cat progress.txt)
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\":\"continue-with-b\",\"client_payload\":{\"start\":\"$NEXT_START\",\"end\":\"${{ inputs.END }}\",\"year\":\"${{ inputs.YEAR }}\"}}"
